#ifndef SRC_NODE_PYTHON_H_
#define SRC_NODE_PYTHON_H_

#if defined(NODE_WANT_INTERNALS) && NODE_WANT_INTERNALS

#endif  // defined(NODE_WANT_INTERNALS) && NODE_WANT_INTERNALS

#endif  // SRC_NODE_PYTHON_H_
